# Next.js Application Supervisor Configuration
[program:nextjs]
command=yarn start
directory=/app
autostart=true
autorestart=true
environment=HOST="0.0.0.0",PORT="3000"
stderr_logfile=/var/log/supervisor/nextjs.err.log
stdout_logfile=/var/log/supervisor/nextjs.out.log
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true
user=root
